name: Build & Push Docker Image

on:
  push:
    branches: [main, master]
    paths:
      - 'Dockerfile'
      - 'pom.xml'
  pull_request:
    branches: [main, master]
    paths:
      - 'Dockerfile'
      - 'pom.xml'

jobs:
  build-and-push-docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t nate338/playwright-java:latest .

      - name: Push Docker image
        run: docker push nate338/playwright-java:latest
