name: Build and Push Playwright Docker Image

on:
  push:
    branches: [main, master]
    paths:
      - 'Dockerfile'
      - 'pom.xml'
      - '.github/workflows/docker-build.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build & Push Docker Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            nate338/playwright-java:latest
            nate338/playwright-java:${{ github.run_number }}

      - name: Verify image pushed
        run: docker pull nate338/playwright-java:latest
