name: Playwright Tests

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types:
      - completed
  push:
    branches: [main, master]
    paths:
      - '**/*.java'
      - '**/*.groovy'
      - '**/src/**'
  pull_request:
    branches: [main, master]
    paths:
      - '**/*.java'
      - '**/*.groovy'
      - '**/src/**'

jobs:
  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    container:
      image: nate338/playwright-java:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup previous reports
        run: rm -rf allure/* extent/* target/* || true

      - name: Build and test
        run: mvn clean verify --no-transfer-progress

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure/reports

      - name: Upload ExtentReports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: extent

      - name: Upload TestNG Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: target/surefire-reports

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure/reports
          publish_branch: gh-pages
          destination_dir: run-${{ github.run_number }}
