name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest
    container:
      image: natek307/playwright-java:latest
      options: --user 1001

    steps:
      - uses: actions/checkout@v4

      - name: Build and test
        run: mvn clean verify --no-transfer-progress

      - name: Upload Surefire reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload Allure results (if you generate them)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
