name: Build Docker & Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-push-docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Dockerfile') || contains(github.event.head_commit.message, 'pom.xml')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t nate338/playwright-java:latest .

      - name: Push Docker image
        run: docker push nate338/playwright-java:latest

  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    needs: [build-and-push-docker]
    container:
      image: nate338/playwright-java:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup previous reports
        run: rm -rf allure/* extent/* target/* || true

      - name: Build and test
        run: mvn clean verify --no-transfer-progress

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure/reports

      - name: Upload ExtentReports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: extent

      - name: Upload TestNG Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: target/surefire-reports

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure/reports
          publish_branch: gh-pages
          destination_dir: run-${{ github.run_number }}
